# Site settings
title: Martin Foot
email: martin@mfoot.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Martin Foot. I am a software engineer with interests in
  photography and historical photographic processes, technology, genetics, and
  evolution.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mfoot.com" # the base hostname & protocol for your site
twitter_username: martinfoot
github_username:  mfoo
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
exclude: [TODO, s3_website.yml]
